# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2024-05-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('sex', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=100, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Должность')),
                ('category', models.CharField(choices=[('Руководитель', 'Руководитель'), ('Специалист', 'Специалист'), ('Служащий', 'Служащий'), ('Рабочий', 'Рабочий')], max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='workers.Position', verbose_name='Должность'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('name', 'birth_date')]),
        ),
    ]
